// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastmr_run_native
Rcpp::List fastmr_run_native(Rcpp::NumericVector exposure_beta, Rcpp::NumericVector outcome_beta, Rcpp::NumericVector exposure_se, Rcpp::NumericVector outcome_se, Rcpp::CharacterVector methods, int nboot, SEXP seed, int threads, double phi, double penk);
RcppExport SEXP _fastMR_fastmr_run_native(SEXP exposure_betaSEXP, SEXP outcome_betaSEXP, SEXP exposure_seSEXP, SEXP outcome_seSEXP, SEXP methodsSEXP, SEXP nbootSEXP, SEXP seedSEXP, SEXP threadsSEXP, SEXP phiSEXP, SEXP penkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type exposure_beta(exposure_betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type outcome_beta(outcome_betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type exposure_se(exposure_seSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type outcome_se(outcome_seSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type methods(methodsSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< SEXP >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type penk(penkSEXP);
    rcpp_result_gen = Rcpp::wrap(fastmr_run_native(exposure_beta, outcome_beta, exposure_se, outcome_se, methods, nboot, seed, threads, phi, penk));
    return rcpp_result_gen;
END_RCPP
}
// fastmr_grid_native
Rcpp::List fastmr_grid_native(Rcpp::NumericMatrix exposure_beta, Rcpp::NumericMatrix outcome_beta, Rcpp::NumericMatrix exposure_se, Rcpp::NumericMatrix outcome_se, Rcpp::CharacterVector methods, int nboot, SEXP seed, int threads, double phi, double penk);
RcppExport SEXP _fastMR_fastmr_grid_native(SEXP exposure_betaSEXP, SEXP outcome_betaSEXP, SEXP exposure_seSEXP, SEXP outcome_seSEXP, SEXP methodsSEXP, SEXP nbootSEXP, SEXP seedSEXP, SEXP threadsSEXP, SEXP phiSEXP, SEXP penkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type exposure_beta(exposure_betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type outcome_beta(outcome_betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type exposure_se(exposure_seSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type outcome_se(outcome_seSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type methods(methodsSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< SEXP >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type penk(penkSEXP);
    rcpp_result_gen = Rcpp::wrap(fastmr_grid_native(exposure_beta, outcome_beta, exposure_se, outcome_se, methods, nboot, seed, threads, phi, penk));
    return rcpp_result_gen;
END_RCPP
}
// fastmr_masked_ivw_native
Rcpp::List fastmr_masked_ivw_native(Rcpp::NumericMatrix exposure_beta, Rcpp::NumericMatrix outcome_beta, Rcpp::NumericMatrix outcome_se, Rcpp::LogicalMatrix exposure_present, Rcpp::LogicalMatrix outcome_present, int threads);
RcppExport SEXP _fastMR_fastmr_masked_ivw_native(SEXP exposure_betaSEXP, SEXP outcome_betaSEXP, SEXP outcome_seSEXP, SEXP exposure_presentSEXP, SEXP outcome_presentSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type exposure_beta(exposure_betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type outcome_beta(outcome_betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type outcome_se(outcome_seSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalMatrix >::type exposure_present(exposure_presentSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalMatrix >::type outcome_present(outcome_presentSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fastmr_masked_ivw_native(exposure_beta, outcome_beta, outcome_se, exposure_present, outcome_present, threads));
    return rcpp_result_gen;
END_RCPP
}
// fastmr_sparse_ivw_native
Rcpp::List fastmr_sparse_ivw_native(Rcpp::IntegerVector row_ptr, Rcpp::IntegerVector col_index, Rcpp::NumericVector exposure_beta, Rcpp::NumericMatrix outcome_beta, Rcpp::NumericMatrix outcome_se, Rcpp::LogicalMatrix outcome_present, int threads);
RcppExport SEXP _fastMR_fastmr_sparse_ivw_native(SEXP row_ptrSEXP, SEXP col_indexSEXP, SEXP exposure_betaSEXP, SEXP outcome_betaSEXP, SEXP outcome_seSEXP, SEXP outcome_presentSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type row_ptr(row_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type col_index(col_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type exposure_beta(exposure_betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type outcome_beta(outcome_betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type outcome_se(outcome_seSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalMatrix >::type outcome_present(outcome_presentSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fastmr_sparse_ivw_native(row_ptr, col_index, exposure_beta, outcome_beta, outcome_se, outcome_present, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastMR_fastmr_run_native", (DL_FUNC) &_fastMR_fastmr_run_native, 10},
    {"_fastMR_fastmr_grid_native", (DL_FUNC) &_fastMR_fastmr_grid_native, 10},
    {"_fastMR_fastmr_masked_ivw_native", (DL_FUNC) &_fastMR_fastmr_masked_ivw_native, 6},
    {"_fastMR_fastmr_sparse_ivw_native", (DL_FUNC) &_fastMR_fastmr_sparse_ivw_native, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastMR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
