# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.fastmr_vcor_read <- function(path, ids) {
    .Call(`_fastMR_fastmr_vcor_read`, path, ids)
}

.fastmr_graph_clump <- function(n_snp, ea, eb, row_snp, exp_start) {
    .Call(`_fastMR_fastmr_graph_clump`, n_snp, ea, eb, row_snp, exp_start)
}

fastmr_run_native <- function(exposure_beta, outcome_beta, exposure_se, outcome_se, methods, nboot = 1000L, seed = NULL, threads = 1L, phi = 1.0, penk = 20.0) {
    .Call(`_fastMR_fastmr_run_native`, exposure_beta, outcome_beta, exposure_se, outcome_se, methods, nboot, seed, threads, phi, penk)
}

fastmr_grid_native <- function(exposure_beta, outcome_beta, exposure_se, outcome_se, methods, nboot = 1000L, seed = NULL, threads = 1L, phi = 1.0, penk = 20.0) {
    .Call(`_fastMR_fastmr_grid_native`, exposure_beta, outcome_beta, exposure_se, outcome_se, methods, nboot, seed, threads, phi, penk)
}

fastmr_masked_ivw_native <- function(exposure_beta, outcome_beta, outcome_se, exposure_present, outcome_present, threads = 1L) {
    .Call(`_fastMR_fastmr_masked_ivw_native`, exposure_beta, outcome_beta, outcome_se, exposure_present, outcome_present, threads)
}

fastmr_sparse_ivw_native <- function(row_ptr, col_index, exposure_beta, outcome_beta, outcome_se, outcome_present, threads = 1L, pair_snp_keep = NULL, steiger_exposure_rsq = NULL, steiger_outcome_rsq = NULL, drop_outcome = NULL, drop_entry = NULL) {
    .Call(`_fastMR_fastmr_sparse_ivw_native`, row_ptr, col_index, exposure_beta, outcome_beta, outcome_se, outcome_present, threads, pair_snp_keep, steiger_exposure_rsq, steiger_outcome_rsq, drop_outcome, drop_entry)
}

fastmr_run_groups_native <- function(offsets, exposure_beta, outcome_beta, exposure_se, outcome_se, methods, nboot = 0L, threads = 1L, phi = 1.0, penk = 20.0) {
    .Call(`_fastMR_fastmr_run_groups_native`, offsets, exposure_beta, outcome_beta, exposure_se, outcome_se, methods, nboot, threads, phi, penk)
}

fastmr_run_groups_boot_native <- function(offsets, exposure_beta, outcome_beta, exposure_se, outcome_se, methods, nboot = 1000L, threads = 1L, phi = 1.0, penk = 20.0, reseed = NULL, batch_draws = 8388608.0) {
    .Call(`_fastMR_fastmr_run_groups_boot_native`, offsets, exposure_beta, outcome_beta, exposure_se, outcome_se, methods, nboot, threads, phi, penk, reseed, batch_draws)
}

