# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastmr_run_native <- function(exposure_beta, outcome_beta, exposure_se, outcome_se, methods, nboot = 1000L, seed = NULL, threads = 1L, phi = 1.0, penk = 20.0) {
    .Call(`_fastMR_fastmr_run_native`, exposure_beta, outcome_beta, exposure_se, outcome_se, methods, nboot, seed, threads, phi, penk)
}

fastmr_grid_native <- function(exposure_beta, outcome_beta, exposure_se, outcome_se, methods, nboot = 1000L, seed = NULL, threads = 1L, phi = 1.0, penk = 20.0) {
    .Call(`_fastMR_fastmr_grid_native`, exposure_beta, outcome_beta, exposure_se, outcome_se, methods, nboot, seed, threads, phi, penk)
}

fastmr_masked_ivw_native <- function(exposure_beta, outcome_beta, outcome_se, exposure_present, outcome_present, threads = 1L) {
    .Call(`_fastMR_fastmr_masked_ivw_native`, exposure_beta, outcome_beta, outcome_se, exposure_present, outcome_present, threads)
}

fastmr_sparse_ivw_native <- function(row_ptr, col_index, exposure_beta, outcome_beta, outcome_se, outcome_present, threads = 1L) {
    .Call(`_fastMR_fastmr_sparse_ivw_native`, row_ptr, col_index, exposure_beta, outcome_beta, outcome_se, outcome_present, threads)
}
